title: brogramming
description: > # this means to ignore newlines until "baseurl:"
  My tech/fitness blog
permalink: ':title/'
baseurl: "/tech-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jack # add your name
author-img: jack.jpg # add your photo
about-author: A brogramming blog - all things javascript, network security, linux, and fitness
github: jzr1991 # add your Github handle

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
